plugins {
    id 'net.fabricmc.fabric-loom' version '1.15'
    id 'maven-publish'
}

version = '1.0.0'
group = 'com.example'

repositories {
    mavenCentral()
    maven {
        name = "Nucleoid"
        url = "https://maven.nucleoid.xyz/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:26.1.2"

    modImplementation "net.fabricmc:fabric-loader:0.18.4"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.100.0+26.1.2"

    // Bundles SGUI into your JAR
    modImplementation include("eu.pb4:sgui:1.6.0+26.1.2")
}